language: scala

scala:
    - 2.11.7

jdk:
    - oraclejdk7

sudo: false

branches:
    only:
        - master

notifications:
    email:
        - leon-dev@googlegroups.com

before_script:
    - sbt compile
    - sbt script
    - source travis/fetchCVC4.sh

env:
    matrix:
        - TEST_COMMAND="test"
        - TEST_COMMAND="integration:test"
        - TEST_COMMAND="regression:test"

script:
    - sbt "$TEST_COMMAND"
